/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../EntityId';
import { NotificationPriority } from '../enums/NotificationPriority';
import { NotificationSound } from '../enums/NotificationSound';

// <keep-imports>
import * as GraphQLJSON from 'graphql-type-json';
// </keep-imports>

@InputType()
export class NotificationCreateInput {
  @Field(() => String, { nullable: true })
  public title?: string | null;

  @Field(() => String, { nullable: true })
  public body?: string | null;

  @Field(() => NotificationPriority)
  public priority: NotificationPriority;

  @Field(() => NotificationSound)
  public sound: NotificationSound;

  @Field(() => Number, { nullable: true })
  public badge?: number | null;

  // <keep-methods>
  @Field(() => [String])
  public channelsNames: Array<string>;

  @Field(() => GraphQLJSON, { nullable: true })
  public data?: object;
  // </keep-methods>
}
