/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../EntityId';

import { ChannelNestedInput } from './ChannelNestedInput';
import { NotificationNestedInput } from './NotificationNestedInput';

// <keep-imports>
// </keep-imports>

@InputType()
export class NotificationChannelEditInput {
  @Field(() => EntityIdScalar)
  public id: EntityId;

  @Field(() => NotificationNestedInput, { nullable: true })
  public notification?: NotificationNestedInput | null;

  @Field(() => ChannelNestedInput, { nullable: true })
  public channel?: ChannelNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
