/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../EntityId';

import { ChannelNestedInput } from './ChannelNestedInput';
import { TokenNestedInput } from './TokenNestedInput';

// <keep-imports>
// </keep-imports>

@InputType()
export class TokenChannelSubscriptionCreateInput {
  @Field(() => TokenNestedInput)
  public token: TokenNestedInput;

  @Field(() => ChannelNestedInput)
  public channel: ChannelNestedInput;

  // <keep-methods>
  // </keep-methods>
}
