/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../EntityId';

import { ChannelNestedInput } from './ChannelNestedInput';
import { TokenNestedInput } from './TokenNestedInput';

// <keep-imports>
// </keep-imports>

@InputType()
export class TokenChannelSubscriptionNestedInput {
  @Field(() => EntityIdScalar, { nullable: true })
  public id?: EntityId;

  @Field(() => TokenNestedInput, { nullable: true })
  public token?: TokenNestedInput | null;

  @Field(() => ChannelNestedInput, { nullable: true })
  public channel?: ChannelNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
