/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length
import { Arg, Args, Ctx, FieldResolver, ID, Info, Mutation, Query, Resolver, Root } from 'type-graphql';

import { addEagerFlags } from '../../utils/add-eager-flags';
import * as auth from '../../utils/auth/auth-checkers';
import { getFindOptions } from '../../utils/get-find-options';
import { EntityId, EntityIdScalar } from '../EntityId';
import { ChannelCreateInput } from '../inputs/ChannelCreateInput';
import { ChannelEditInput } from '../inputs/ChannelEditInput';
import { IRequestContext } from '../IRequestContext';
import { Channel } from '../models/Channel';

// <keep-imports>
// </keep-imports>

@Resolver(Channel)
export class ChannelCrudResolver {
  @Query((returns) => Channel)
  public async channel(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.findOneOrFail(Channel, id, getFindOptions(Channel, info)));
  }

  @Query((returns) => [Channel])
  public async channels(@Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.find(Channel, getFindOptions(Channel, info)));
  }

  @Mutation((returns) => Channel)
  public async createChannel(@Arg('input') input: ChannelCreateInput, @Ctx() ctx: IRequestContext): Promise<Channel> {
    const model = new Channel();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    // <keep-create-code>
    // </keep-create-code>

    return model;
  }

  @Mutation((returns) => Channel)
  public async updateChannel(@Arg('input') input: ChannelEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(Channel, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation((returns) => Boolean)
  public async deleteChannels(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(Channel, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
