/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length
import { Arg, Args, Ctx, FieldResolver, ID, Info, Mutation, Query, Resolver, Root } from 'type-graphql';

import { addEagerFlags } from '../../utils/add-eager-flags';
import * as auth from '../../utils/auth/auth-checkers';
import { getFindOptions } from '../../utils/get-find-options';
import { EntityId, EntityIdScalar } from '../EntityId';
import { NotificationChannelCreateInput } from '../inputs/NotificationChannelCreateInput';
import { NotificationChannelEditInput } from '../inputs/NotificationChannelEditInput';
import { IRequestContext } from '../IRequestContext';
import { NotificationChannel } from '../models/NotificationChannel';

// <keep-imports>
// </keep-imports>

@Resolver(NotificationChannel)
export class NotificationChannelCrudResolver {
  @Query((returns) => NotificationChannel)
  public async notificationChannel(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.findOneOrFail(NotificationChannel, id, getFindOptions(NotificationChannel, info)));
  }

  @Query((returns) => [NotificationChannel])
  public async notificationChannels(@Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.find(NotificationChannel, getFindOptions(NotificationChannel, info)));
  }

  @Mutation((returns) => NotificationChannel)
  public async createNotificationChannel(@Arg('input') input: NotificationChannelCreateInput, @Ctx() ctx: IRequestContext): Promise<NotificationChannel> {
    const model = new NotificationChannel();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    // <keep-create-code>
    // </keep-create-code>

    return model;
  }

  @Mutation((returns) => NotificationChannel)
  public async updateNotificationChannel(@Arg('input') input: NotificationChannelEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(NotificationChannel, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation((returns) => Boolean)
  public async deleteNotificationChannels(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(NotificationChannel, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
