/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length
import { Arg, Args, Ctx, FieldResolver, ID, Info, Mutation, Query, Resolver, Root } from 'type-graphql';

import { addEagerFlags } from '../../utils/add-eager-flags';
import * as auth from '../../utils/auth/auth-checkers';
import { getFindOptions } from '../../utils/get-find-options';
import { EntityId, EntityIdScalar } from '../EntityId';
import { TokenChannelSubscriptionCreateInput } from '../inputs/TokenChannelSubscriptionCreateInput';
import { TokenChannelSubscriptionEditInput } from '../inputs/TokenChannelSubscriptionEditInput';
import { IRequestContext } from '../IRequestContext';
import { TokenChannelSubscription } from '../models/TokenChannelSubscription';

// <keep-imports>
// </keep-imports>

@Resolver(TokenChannelSubscription)
export class TokenChannelSubscriptionCrudResolver {
  @Query((returns) => TokenChannelSubscription)
  public async tokenChannelSubscription(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.findOneOrFail(TokenChannelSubscription, id, getFindOptions(TokenChannelSubscription, info)));
  }

  @Query((returns) => [TokenChannelSubscription])
  public async tokenChannelSubscriptions(@Info() info, @Ctx() ctx: IRequestContext) {
    return addEagerFlags(await ctx.em.find(TokenChannelSubscription, getFindOptions(TokenChannelSubscription, info)));
  }

  @Mutation((returns) => TokenChannelSubscription)
  public async createTokenChannelSubscription(@Arg('input') input: TokenChannelSubscriptionCreateInput, @Ctx() ctx: IRequestContext): Promise<TokenChannelSubscription> {
    const model = new TokenChannelSubscription();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    // <keep-create-code>
    // </keep-create-code>

    return model;
  }

  @Mutation((returns) => TokenChannelSubscription)
  public async updateTokenChannelSubscription(@Arg('input') input: TokenChannelSubscriptionEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(TokenChannelSubscription, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation((returns) => Boolean)
  public async deleteTokenChannelSubscriptions(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(TokenChannelSubscription, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
