/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { registerEnumType } from 'type-graphql';

export enum NotificationPriority {
  default = 'default',
  normal = 'normal',
  high = 'high',
}

registerEnumType(NotificationPriority, {
  name: 'NotificationPriority',
});
