/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { registerEnumType } from 'type-graphql';

export enum NotificationSound {
  default = 'default',
  none = 'none',
}

registerEnumType(NotificationSound, {
  name: 'NotificationSound',
});
