/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
// tslint:disable max-line-length no-duplicate-imports
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, Entity, JoinColumn, ManyToOne, OneToMany, OneToOne, PrimaryGeneratedColumn } from 'typeorm';

import { Channel } from './Channel';
import { Token } from './Token';

import * as auth from '../../utils/auth/auth-checkers';
import { IAuthorizable } from '../../utils/auth/IAuthorizable';
import { getInputOperationType } from '../../utils/get-input-operation-type';
import { TokenChannelSubscriptionAuth } from '../auth/TokenChannelSubscriptionAuth';
import { EntityId, EntityIdScalar } from '../EntityId';
import { TokenChannelSubscriptionCreateInput } from '../inputs/TokenChannelSubscriptionCreateInput';
import { TokenChannelSubscriptionEditInput } from '../inputs/TokenChannelSubscriptionEditInput';
import { TokenChannelSubscriptionNestedInput } from '../inputs/TokenChannelSubscriptionNestedInput';
import { IRequestContext } from '../IRequestContext';
import { updateChannelRelation, updateTokenRelation } from './update-operations/tokenChannelSubscription-update-operations';

// <keep-imports>
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class TokenChannelSubscription implements IAuthorizable {
  @Field((type) => EntityIdScalar)
  @PrimaryGeneratedColumn()
  public id: EntityId;

  public authorizationChecker = new TokenChannelSubscriptionAuth(this);

  @ManyToOne((type) => Token, (token) => token.subscriptions , { nullable: false, onDelete: 'CASCADE' })
  @Field((returns) => Token , { nullable: false })
  public token: Promise<Token>;

  @ManyToOne((type) => Channel, (channel) => channel.subscriptions , { nullable: false, onDelete: 'CASCADE' })
  @Field((returns) => Channel , { nullable: false })
  public channel: Promise<Channel>;

  public async update(input: TokenChannelSubscriptionCreateInput | TokenChannelSubscriptionEditInput | TokenChannelSubscriptionNestedInput, context: IRequestContext) {
    const { token, channel, ...data } = input;
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    await updateTokenRelation(this, token, context);
    await updateChannelRelation(this, channel, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  // </keep-methods>
}
